export const CHAT_SERVER_URL = process.env.NEXT_PUBLIC_CHAT_SERVER_URL
export const IMAGES_BASE_URL = process.env.NEXT_PUBLIC_BASE_IMG_URL
export const FILES_BASE_URL = process.env.NEXT_PUBLIC_BASE_FILE_URL
export const ACCESS_TOKEN_EXPIRATION_DAYS = Number(process.env.NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_DAYS)
export const REFRESH_TOKEN_EXPIRATION_DAYS = Number(process.env.NEXT_PUBLIC_REFRESH_TOKEN_EXPIRE_DAYS) 
