export const ACCESS_TOKEN_EXPIRATION_DAYS = Number(process.env.NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_DAYS)
export const REFRESH_TOKEN_EXPIRATION_DAYS = Number(process.env.NEXT_PUBLIC_REFRESH_TOKEN_EXPIRE_DAYS) 
